apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: llm-pool
  namespace: llm-d-inference
spec:
  targetPortNumber: 8000
  selector:
    app: vllm
  extensionRef:
    name: llm-pool-epp
    group: ""
    kind: Service
